//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User_Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User_Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.User.User_Shared", typeof(User_Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前用户：.
        /// </summary>
        public static string UserSite_currentUser {
            get {
                return ResourceManager.GetString("UserSite_currentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string UserSite_logout {
            get {
                return ResourceManager.GetString("UserSite_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改信息.
        /// </summary>
        public static string UserSite_modifyInfo {
            get {
                return ResourceManager.GetString("UserSite_modifyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息.
        /// </summary>
        public static string UserSite_personInfo {
            get {
                return ResourceManager.GetString("UserSite_personInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 能耗查询.
        /// </summary>
        public static string UserSite_queryEnergy {
            get {
                return ResourceManager.GetString("UserSite_queryEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复旦大学绿色校园能耗监控平台.
        /// </summary>
        public static string UserSite_siteName {
            get {
                return ResourceManager.GetString("UserSite_siteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子功能.
        /// </summary>
        public static string UserSite_subFun {
            get {
                return ResourceManager.GetString("UserSite_subFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户信息.
        /// </summary>
        public static string UserSite_userInfo {
            get {
                return ResourceManager.GetString("UserSite_userInfo", resourceCulture);
            }
        }
    }
}
